### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by knightphoenix** [glynhudson/metoffice-emoncms#1]
For the section https://github.com/glynhudson/metoffice-emoncms#create-cron-job-to-run-every-hour

The command should read "crontab -e" not "contab -e"
![contab](https://github.com/glynhudson/metoffice-emoncms/assets/27956778/ae5790e1-6a29-4ed2-a527-27ea6a99a766)

**Comment by glynhudson** [comment]
Thanks
